pipeline {
	agent {
		node {
			label "Java"
		}
	}

	environment {
		// details
	}

	stages {
		stage("Build"){
			steps{
				//build steps
			}
		}
		stage("Publish"){
			steps{
				//publish steps
			}
		}
	}
}
