version: "3.3"

volumes:
        db-data:

networks:
        instavote:
                driver: bridge


services:

        vote:
                image: hugoaquinonavarrete/vote:master
                ports:
                        - 5000:80
                depends_on:
                        - redis                        
                networks:
                        - instavote

        redis:
                image: redis:alpine
                networks:
                        - instavote

        db:
                image: postgres:9.4
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: postgres
                volumes:
                        - "db-data:/var/lib/postgresql/data"
                networks:
                        - instavote

        result:
                image: hugoaquinonavarrete/result:master
                ports:
                        - 5001:4000
                depends_on:
                        - db
                networks:
                        - instavote

        worker:
                image: hugoaquinonavarrete/worker:master
                depends_on:
                        - redis
                        - db
                networks:
                        - instavote
